# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Tutorial7',
                'doc_host': 'https://annammckinney.github.io',
                'git_url': 'https://github.com/annammckinney/Tutorial7',
                'lib_path': 'Tutorial7'},
  'syms': {'Tutorial7.core': {'Tutorial7.core.foo': ('core.html#foo', 'Tutorial7/core.py')}}}